In [1]:
import sqlite3
import pandas as pd

In [2]:
PATH = '../data/casino_sim.db'
conn = sqlite3.connect(PATH)

In [3]:
df = pd.read_sql_query("""
        SELECT player_id, SUM(bet) as bets,  SUM(win) as wins, SUM(bet) - SUM(win) as profit
        FROM spins
        GROUP BY player_id
                       """, conn)

df

    player_id     bets     wins  profit
0           1  10000.0  10060.0   -60.0
1           2  10000.0   6570.0  3430.0
2           3  10000.0   9470.0   530.0
3           4  10000.0   9570.0   430.0
4           5  10000.0  10060.0   -60.0
5           6  10000.0   6820.0  3180.0
6           7  10000.0  11710.0 -1710.0
7           8  10000.0  10390.0  -390.0
8           9  10000.0   8770.0  1230.0
9          10  10000.0   9840.0   160.0
10         11  10000.0   9180.0   820.0
11         12  10000.0   6950.0  3050.0
12         13  10000.0   9100.0   900.0
13         14  10000.0   7700.0  2300.0
14         15  10000.0   8630.0  1370.0
15         16  10000.0  10280.0  -280.0
16         17  10000.0   9070.0   930.0
17         18  10000.0   9870.0   130.0
18         19  10000.0  10630.0  -630.0
19         20  10000.0   6150.0  3850.0
20         21  10000.0   9740.0   260.0
21         22  10000.0   7280.0  2720.0
22         23  10000.0  10500.0  -500.0
23         24  10000.0   8190.0  1810.0
24         25  10000.0  10410.0  -410.0
25         26  10000.0   8960.0  1040.0
26         27  10000.0   8410.0  1590.0
27         28  10000.0  10410.0  -410.0
28         29  10000.0   9650.0   350.0
29         30  10000.0   8500.0  1500.0
30         31  10000.0   6870.0  3130.0
31         32  10000.0   8820.0  1180.0
32         33  10000.0   9040.0   960.0
33         34  10000.0   9020.0   980.0
34         35  10000.0   8210.0  1790.0
35         36  10000.0  11160.0 -1160.0
36         37  10000.0  10150.0  -150.0
37         38  10000.0   9440.0   560.0
38         39  10000.0   6900.0  3100.0
39         40  10000.0  11640.0 -1640.0
40         41  10000.0   9760.0   240.0
41         42  10000.0   7720.0  2280.0
42         43  10000.0   6650.0  3350.0
43         44  10000.0   8380.0  1620.0
44         45  10000.0   8770.0  1230.0
45         46  10000.0   7590.0  2410.0
46         47  10000.0  11370.0 -1370.0
47         48  10000.0   9530.0   470.0
48         49  10000.0   9490.0   510.0
49         50  10000.0   8890.0  1110.0

In [4]:
df.describe()

       player_id     bets          wins       profit
count   50.00000     50.0     50.000000    50.000000
mean    25.50000  10000.0   9045.400000   954.600000
std     14.57738      0.0   1378.511783  1378.511783
min      1.00000  10000.0   6150.000000 -1710.000000
25%     13.25000  10000.0   8252.500000   -12.500000
50%     25.50000  10000.0   9085.000000   915.000000
75%     37.75000  10000.0  10012.500000  1747.500000
max     50.00000  10000.0  11710.000000  3850.000000

In [18]:
df['profit'].sum()

np.float64(47730.0)

np.float64(954.6)